version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - laravel
    ports:
      - "8000:80"

  db:
    image: postgres:latest
    container_name: laravel_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: primeiro_projeto
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    networks:
      - laravel

networks:
  laravel:


